# Generated by Django 3.2.9 on 2022-06-25 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soc_members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Executive Committee', 'Executive Committee'), ('Finance Committee', 'Finance Committee'), ('Constitutional Committee', 'Constitutional Committee'), ('Disciplinary Committee', 'Disciplinary Committee'), ('Events Committee', 'Events Committee'), ('Compassion Committee', 'Compassion Committee')], max_length=200)),
                ('shortname', models.CharField(choices=[('EXCO', 'EXCO'), ('FINCOM', 'FINCOM'), ('CONCOM', 'CONCOM'), ('DC', 'DC'), ('COMPCOM', 'COMPCOM'), ('ECOM', 'ECOM')], max_length=100)),
                ('term_starts', models.DateField()),
                ('term_ends', models.DateField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Incumbent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.CharField(choices=[('Chairperson', 'Chairperson'), ('Deputy Chairperson', 'Deputy Chairperson'), ('Secetary-General', 'Secretary-General'), ('Deputy Secretary-General', 'Deputy Secretary-General'), ('Treasurer-General', 'Treasurer-General'), ('Events Coordinator', 'Events Cordinator'), ('Member of EXCO', 'Member of Exco'), ('Convenor', 'Convenor'), ('Member', 'Member'), ('Ex Officio Member', 'Ex Officio Member')], max_length=200)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incumbents', to='soc_committees.committee')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soc_members.member')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
