# Generated by Django 3.2.9 on 2022-06-14 10:21

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soc_members', '0009_alter_beneficiary_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('date', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receipts', to='soc_members.member')),
            ],
        ),
        migrations.CreateModel(
            name='MemberAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('balance_brought_forward', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('premiums', models.DecimalField(decimal_places=2, default=Decimal('150.0'), max_digits=10)),
                ('funeral_topup', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('transport_topup', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('total_fines', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('total_debits', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=10, null=True)),
                ('cash_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('adjustments', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('total_receipts', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=10, null=True)),
                ('net_movement', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='soc_members.member')),
            ],
            options={
                'ordering': ['-date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Debits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('debit_type', models.CharField(choices=[(None, 'Select debit type'), ('meeting absence', 'Meeting absence'), ('funeral absence', 'Funeral absence'), ('uniform', 'Uniform'), ('disciplinary action', 'Disciplinary Action'), ('funeral topup', 'Funeral topup'), ('transport augmentation', 'Transport augmentation')], max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='debits', to='soc_members.member')),
            ],
        ),
    ]
