# Generated by Django 3.2.9 on 2022-06-25 19:51

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soc_members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('balance_brought_forward', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('premiums', models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=10)),
                ('fines', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('topups', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('total_debits', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('cash_deposits', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('adjustments', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('total_receipts', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True)),
                ('net_movement', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_outstanding', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='soc_members.member')),
            ],
            options={
                'ordering': ['-date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Topup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('topup_type', models.CharField(choices=[(None, 'Select top-up type'), ('funeral topup', 'Funeral Topup'), ('transport augmentation', 'Transport Augmentation'), ('special function', 'Special Function')], max_length=250)),
                ('description', models.CharField(blank=True, max_length=350, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_topups', to='soc_finance.memberaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_type', models.CharField(choices=[(None, 'Select fine type'), ('meeting absence', 'Meeting Absence'), ('funeral absence', 'Funeral Absence'), ('late coming', 'Late Coming'), ('uniform', 'Uniform'), ('disciplinary action', 'Disciplinary Action')], max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_fines', to='soc_finance.memberaccount')),
            ],
        ),
    ]
