# Generated by Django 3.2.9 on 2022-06-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc_finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberaccount',
            old_name='cash_deposit',
            new_name='cash_deposits',
        ),
        migrations.RenameField(
            model_name='memberaccount',
            old_name='funeral_topup',
            new_name='other_debits',
        ),
        migrations.RemoveField(
            model_name='memberaccount',
            name='total_fines',
        ),
        migrations.RemoveField(
            model_name='memberaccount',
            name='transport_topup',
        ),
        migrations.AlterField(
            model_name='debits',
            name='debit_type',
            field=models.CharField(choices=[(None, 'Select debit type'), ('meeting absence', 'Meeting Absence'), ('funeral absence', 'Funeral Absence'), ('late coming', 'Late Coming'), ('uniform', 'Uniform'), ('disciplinary action', 'Disciplinary Action'), ('funeral topup', 'Funeral Topup'), ('transport augmentation', 'Transport Augmentation')], max_length=200),
        ),
    ]
