# Generated by Django 3.2.9 on 2022-06-14 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soc_finance', '0002_auto_20220614_1608'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Debits',
            new_name='Debit',
        ),
        migrations.RenameModel(
            old_name='Receipts',
            new_name='Receipt',
        ),
        migrations.AlterField(
            model_name='debit',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='debits', to='soc_finance.memberaccount'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='receipts', to='soc_finance.memberaccount'),
        ),
    ]
