# Generated by Django 3.2.9 on 2022-06-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc_finance', '0003_auto_20220614_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debit',
            name='debit_type',
            field=models.CharField(choices=[(None, 'Select debit type'), ('meeting absence', 'Meeting Absence'), ('funeral absence', 'Funeral Absence'), ('late coming', 'Late Coming'), ('uniform', 'Uniform'), ('disciplinary action', 'Disciplinary Action'), ('funeral topup', 'Funeral Topup'), ('transport augmentation', 'Transport Augmentation')], max_length=300),
        ),
        migrations.AlterField(
            model_name='debit',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
