# Generated by Django 3.2.9 on 2022-06-25 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Deceased', 'Deceased'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated')], default='Active', max_length=15)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('cover_lapse_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(max_length=200)),
                ('photo', models.ImageField(default='static/img/default2.png', upload_to='member_photos/%Y')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user_id',),
            },
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=400)),
                ('beneficiary_type', models.CharField(choices=[('Spouse', 'Spouse'), ('Child', 'Child'), ('Father', 'Father'), ('Mother', 'Mother'), ('Father-in-Law', 'Father-in-Law'), ('Mother-in-Law', 'Mother-in-Law'), ('Parent Proxy', 'Parent Proxy'), ('Other', 'Other')], default='Spouse', max_length=100, verbose_name='Beneficiary Type')),
                ('proxy', models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Father-in_Law', 'Father-in-Law'), ('Mother-in-Law', 'Mother-in-Law'), ('Other', 'Other')], max_length=100, null=True)),
                ('birth_date', models.DateField(verbose_name='Date of Birth')),
                ('beneficiary_status', models.CharField(choices=[('Active', 'Active'), ('Deceased', 'Deceased'), ('Inactive', 'Inactive')], default='Active', max_length=100, verbose_name='Beneficiary Status')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid-up')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid-up Date')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='soc_members.member')),
            ],
            options={
                'verbose_name_plural': 'Beneficiaries',
                'ordering': ('id',),
            },
        ),
    ]
