# Generated by Django 3.2 on 2021-11-27 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middlename', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(null=True)),
                ('mobile_phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=15)),
                ('inactive_status_reason', models.CharField(blank=True, choices=[('Deceased', 'Deceased'), ('Suspended', 'Suspeded'), ('Terminated', 'Terminated')], max_length=20, null=True)),
                ('status_date', models.DateField(blank=True, null=True)),
                ('cover_lapse_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(max_length=200)),
                ('photo', models.ImageField(default='static/img/default2.png', upload_to='member_photos/%Y')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
