# Generated by Django 3.2.9 on 2022-05-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc_members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='inactive_status_reason',
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Deceased', 'Deceased'), ('Suspended', 'Suspeded'), ('Terminated', 'Terminated')], default='Active', max_length=15),
        ),
    ]
