# Generated by Django 3.2.9 on 2022-06-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc_members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(default='default2.png', upload_to='member_photos/%Y'),
        ),
    ]
