# Generated by Django 3.2.9 on 2022-05-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc_members', '0003_beneficiary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deceased', 'Deceased'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated')], default='Active', max_length=100, verbose_name='Beneficiary Status'),
        ),
    ]
