# Generated by Django 3.2.9 on 2022-05-29 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc_members', '0004_alter_beneficiary_beneficiary_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Deceased', 'Deceased'), ('Suspended', 'Suspended'), ('Terminated', 'Terminated')], default='Active', max_length=15),
        ),
    ]
