# Generated by Django 3.2.9 on 2022-06-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc_members', '0005_alter_member_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('user_id',)},
        ),
        migrations.AddField(
            model_name='member',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deceased', 'Deceased'), ('Inactive', 'Inactive')], default='Active', max_length=100, verbose_name='Beneficiary Status'),
        ),
    ]
