# Generated by Django 3.2.9 on 2022-06-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc_members', '0007_auto_20220606_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
