# Generated by Django 3.2.9 on 2022-06-13 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc_members', '0008_member_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='full_name',
            field=models.CharField(max_length=400),
        ),
    ]
