# Generated by Django 3.2.9 on 2022-06-09 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soc_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minutes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('doc_file', models.FileField(upload_to='minutes/%Y/%F')),
                ('uploaded_by', models.CharField(editable=False, max_length=200)),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meeting', to='soc_events.meeting')),
            ],
            options={
                'verbose_name_plural': 'Minutes',
            },
        ),
    ]
