# Generated by Django 3.2.9 on 2022-06-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc_documents', '0002_alter_minutes_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes',
            name='uploaded_by',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
