# Generated by Django 3.2.9 on 2022-06-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc_documents', '0004_auto_20220612_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='minutes',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
