# Generated by Django 3.2.9 on 2022-06-08 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soc_members', '0008_member_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('deceased_type', models.CharField(choices=[('Member', 'Member'), ('Beneficiary', 'Beneficiary')], max_length=100)),
                ('venue', models.CharField(max_length=200)),
                ('bereaved_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soc_members.member')),
                ('deceased_beneficiary', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soc_members.beneficiary')),
                ('deceased_member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meeting_type', models.CharField(choices=[('Quartely Meeting', 'Quartely Meeting'), ('Special Meeting', 'Special Meeting'), ('Year-end Function', 'Year-end Function'), ('Extraordinary Meeting', 'Extraordinary Meeting')], max_length=200)),
                ('alt_venue', models.CharField(blank=True, max_length=300, null=True)),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meetings', to='soc_members.member')),
            ],
        ),
        migrations.CreateModel(
            name='FuneralAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True)),
                ('absence_reason', models.CharField(blank=True, choices=[('Family Commitment', 'Family Commitment'), ('Ill-Health', 'Ill-Health'), ('Work Commitment', 'Work Commitment'), ('Funeral Attendance', 'Funeral Attendance')], max_length=300, null=True)),
                ('funeral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='soc_events.funeral')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='soc_members.member')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True)),
                ('absence_reason', models.CharField(blank=True, choices=[('Family Commitment', 'Family Commitment'), ('Ill-Health', 'Ill-Health'), ('Work Commitment', 'Work Commitment'), ('Funeral Attendance', 'Funeral Attendance')], max_length=300, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='soc_events.meeting')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='soc_members.member')),
            ],
        ),
    ]
