# Generated by Django 3.2.9 on 2022-06-22 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soc_members', '0009_alter_beneficiary_full_name'),
        ('soc_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=True)),
                ('absence_reason', models.CharField(blank=True, choices=[('Family Commitment', 'Family Commitment'), ('Ill-Health', 'Ill-Health'), ('Work Commitment', 'Work Commitment'), ('Funeral Attendance', 'Funeral Attendance')], max_length=300, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='soc_events.meeting')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_meetings', to='soc_members.member')),
            ],
        ),
        migrations.AlterField(
            model_name='funeral',
            name='bereaved_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bereaved', to='soc_members.member'),
        ),
        migrations.AlterField(
            model_name='funeral',
            name='deceased_member',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='soc_members.member'),
        ),
        migrations.AlterField(
            model_name='funeralattendance',
            name='absence_reason',
            field=models.CharField(blank=True, choices=[('Family Commitment', 'Family Commitment'), ('Ill-Health', 'Ill-Health'), ('Work Commitment', 'Work Commitment'), ('Funeral', 'Funeral')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='funeralattendance',
            name='funeral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funerals', to='soc_events.funeral'),
        ),
        migrations.AlterField(
            model_name='funeralattendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_funerals', to='soc_members.member'),
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
