# Generated by Django 3.2.9 on 2022-06-23 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soc_events', '0002_auto_20220622_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funeralattendance',
            name='funeral',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funeral_attendances', to='soc_events.funeral'),
        ),
        migrations.AlterField(
            model_name='meetingattendance',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendances', to='soc_events.meeting'),
        ),
    ]
