# Generated by Django 3.2.9 on 2022-06-23 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soc_events', '0003_auto_20220623_1355'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ('-date',)},
        ),
    ]
