# Generated by Django 3.2.9 on 2021-12-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soc_members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('beneficiary_type', models.CharField(choices=[('Spouse', 'Spouse'), ('Child', 'Child'), ('Father', 'Father'), ('Mother', 'Mother'), ('Father-in-Law', 'Father-in-Law'), ('Mother-in-Law', 'Mother-in-Law'), ('Parent Proxy', 'Parent Proxy')], default='Spouse', max_length=100)),
                ('proxy', models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Father-in_Law', 'Father-in-Law'), ('Mother-in-Law', 'Mother-in-Law')], max_length=100, null=True)),
                ('birth_date', models.DateField()),
                ('beneficiary_status', models.CharField(choices=[('Active', 'Active'), ('Article 20.3', 'Article 20.3'), ('Deceased', 'Deceased'), ('Inactive', 'Inactive')], default='Active', max_length=100)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='soc_members.member')),
            ],
            options={
                'verbose_name_plural': 'Beneficiaries',
                'ordering': ('member__id',),
            },
        ),
    ]
