# Generated by Django 3.2.9 on 2022-06-25 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soc_members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256)),
                ('beneficiary_type', models.CharField(choices=[('Spouse', 'Spouse'), ('Child', 'Child'), ('Father', 'Father'), ('Mother', 'Mother'), ('Father-in-Law', 'Father-in-Law'), ('Mother-in-Law', 'Mother-in-Law'), ('Parent Proxy', 'Parent Proxy'), ('Other', 'Other')], default='Spouse', max_length=100, verbose_name='Beneficiary Type')),
                ('proxy', models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Father-in_Law', 'Father-in-Law'), ('Mother-in-Law', 'Mother-in-Law'), ('Other', 'Other')], max_length=100, null=True)),
                ('birth_date', models.DateField(verbose_name='Date of Birth')),
                ('beneficiary_status', models.CharField(choices=[('Active', 'Active'), ('Deceased', 'Deceased'), ('Inactive', 'Inactive')], default='Active', max_length=100, verbose_name='Beneficiary Status')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Paid-up')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Paid-up Date')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benes', to='soc_members.member')),
            ],
            options={
                'verbose_name_plural': 'Beneficiaries',
                'ordering': ('id',),
            },
        ),
    ]
