# Generated by Django 3.2.9 on 2022-05-13 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc_beneficiaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='beneficiary',
            options={'ordering': ('id',), 'verbose_name_plural': 'Beneficiaries'},
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Paid-up'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Paid-up date'),
        ),
    ]
