# Generated by Django 3.2.9 on 2022-05-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soc_beneficiaries', '0002_auto_20220513_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beneficiary',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Deceased', 'Deceased'), ('Inactive', 'Inactive')], default='Active', max_length=100, verbose_name='Beneficiary Status'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='beneficiary_type',
            field=models.CharField(choices=[('Spouse', 'Spouse'), ('Child', 'Child'), ('Father', 'Father'), ('Mother', 'Mother'), ('Father-in-Law', 'Father-in-Law'), ('Mother-in-Law', 'Mother-in-Law'), ('Parent Proxy', 'Parent Proxy'), ('Other', 'Other')], default='Spouse', max_length=100, verbose_name='Beneficiary Type'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='birth_date',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Paid-up Date'),
        ),
        migrations.AlterField(
            model_name='beneficiary',
            name='proxy',
            field=models.CharField(blank=True, choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Father-in_Law', 'Father-in-Law'), ('Mother-in-Law', 'Mother-in-Law'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
