# Generated by Django 3.2.9 on 2022-05-17 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('soc_members', '0003_beneficiary'),
        ('soc_beneficiaries', '0003_auto_20220514_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benes', to='soc_members.member'),
        ),
    ]
